
data class Post(
    var id: Int = 1,
    val ownerId: Int = 1,
    val fromId: Int = 2,
    val createdBy: Int = 3,
    val date: UInt = 4U,
    val text: String = "Post",
    val replyOwnerId: Int = 5,
    val replyPostId: Int = 6,
    val friendsOnly: Boolean = true,
    val comments: Int = 1,
    val copyright: Int = 1,
    val likes: UInt = 1u,
    val reposts: Int = 1,
    val views: Int = 1,
    val postType: String = "Normal",
    val postSource: PostSource?,
    val attachments: Array<Attachments>,
    val geo: Any?,
    val singerID: Int = 7,
    val copyHistory: Array<String>,
    val canPin: Boolean = true,
    val canDelete: Boolean = true,
    val canEdit: Boolean = true,
    val isPinned: Boolean = true,
    val markedAsAds: Boolean = true,
    val isFavorite: Boolean= true,
    val donut: Donat?,
    val postponedId: Int = 8
)